---
version: 2
project_name: ci-thief
before:
  hooks:
    - go mod tidy
builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
homebrew_casks:
  - repository:
      owner: containeroo
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
      branch: master
    homepage: https://containeroo.ch
    description: Simple CLI tool to fetch GitLab CI variables and output them as exportable environment variables.
    license: GNU General Public License v3.0
