---
version: 2
project_name: ci-thief
before:
  hooks:
    - go mod tidy
    - mkdir -p completions
    - sh -c "go run . completion bash > completions/ci-thief.bash"
    - sh -c "go run . completion zsh > completions/ci-thief.zsh"
builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - files:
      - README*
      - LICENSE*
      - completions/*
homebrew_casks:
  - repository:
      owner: containeroo
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
      branch: master
    homepage: https://containeroo.ch
    description: Simple CLI tool to fetch GitLab CI variables and output them as exportable environment variables.
    license: GNU General Public License v3.0
    binaries:
      - ci-thief
    completions:
      bash: completions/ci-thief.bash
      zsh: completions/ci-thief.zsh
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ci-thief"]
          end
