---
project_name: ci-thief
before:
  hooks:
    - go mod tidy
builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
brews:
  - name: ci-thief
    repository:
      owner: containeroo
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: https://containeroo.ch
    description: Simple CLI tool to fetch GitLab CI variables and output them as exportable environment variables.
    license: GNU General Public License v3.0
    test: |
      system "#{bin}/ci-thief version"
    dependencies:
      - name: go
        type: optional
    install: |-
      bin.install "ci-thief"

      # Install bash completion
      output = Utils.safe_popen_read(bin/"ci-thief", "completion", "bash")
      (bash_completion/"ci-thief").write output

      # Install zsh completion
      output = Utils.safe_popen_read(bin/"ci-thief", "completion", "zsh")
      (zsh_completion/"_ci-thief").write output
